### ISSUE TITLE
Create Settings Page separate from Personal Details Page

### ISSUE THREAD

**Issue by FlaIespa** [ucey-star/ID8#24]
@avalucianelson 
#17
As you mentioned, given that the Settings and Personal Details have the same functionality, they can use the same component. I believe it would make sense to create them separately but using the same component so the routing does not get confused. I might be wrong in this and would welcome any suggestions. Just ensuring that the comment raised in the PR is addressed at some point in development.

**Comment by avalucianelson** [comment]
No longer necessary. Discussed with team, makes sense to leave as is given latest changes & the fact that we will not be introducing any new functionality on the "settings" page (will be exact same page as "Personal Details"
