### ISSUE TITLE
HomePage refactored to use the / route

### ISSUE THREAD

**Issue by FlaIespa** [ucey-star/ID8#28]
@mchudyk 
Move the code from app/home/page.tsx to app/page.tsx to ensure that the default route is the home page.

**Comment by Mykhailo-Chudyk** [comment]
We have this new page now, so I assume this issue is no longer relevant. Right, @FlaIespa?

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/90c25057-2cf8-48ea-836a-1dd978a3f093">

**Comment by FlaIespa** [comment]
> We have this new page now, so I assume this issue is no longer relevant. Right, @FlaIespa?
> 
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/102920272/391364978-90c25057-2cf8-48ea-836a-1dd978a3f093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMDIzMDAsIm5iZiI6MTczNDMwMjAwMCwicGF0aCI6Ii8xMDI5MjAyNzIvMzkxMzY0OTc4LTkwYzI1MDU3LTJjZjgtNDhlYS04MzZhLTFkZDk3OGEzZjA5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQyMjMzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDYwNmJhM2IzZmIxMjMxOTQ3ZmRjZDEzMDliN2U4MjUzYjc4YzkyNDJiZWIzZTI3MjBjYWRiNDY5MjY4Zjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cXFJQVTFbxT5jBRpiHBnSFwdE1M_4w8pRdzjWn0gMqI">

Yes! You are right :)
