### ISSUE TITLE
"Use Client" issue

### ISSUE THREAD

**Issue by Mykhailo-Chudyk** [ucey-star/ID8#37]
![image](https://github.com/user-attachments/assets/5a2897f9-9c6d-45b9-9ca1-bc8d1cbc3b00)

**Comment by ucey-star** [comment]
Hey @matviikotolyk! I assigned this to you because you wrote this line of code that causes the deployment error

`import React, { useState } from "react";`

Please take a look!

**Comment by matviikotolyk** [comment]
here's the PR: https://github.com/ucey-star/ID8/pull/38
