### ISSUE TITLE
Project Idea Form Improvements

### ISSUE THREAD

**Issue by lewiskyron** [ucey-star/ID8#39]
The text field for the tagline(150 characters or less) gets quite crowded and makes if difficult to see what is written at once. We need this to be addressed and for the character counter to be shown as the user types. This will improve users experience and make the process of filling out project details more pleasant. 

<img width="593" alt="Screenshot 2024-11-17 at 5 29 05 PM" src="https://github.com/user-attachments/assets/d903d50f-9dc9-45da-b030-5c7da39c9a0a">

**Comment by matviikotolyk** [comment]
@FlaIespa i can take this one if that works!

**Comment by FlaIespa** [comment]
> @FlaIespa i can take this one if that works!

Only saw that now! Yes. That would be really nice :)

**Comment by matviikotolyk** [comment]
here's the PR for this issue @lewiskyron @FlaIespa
