### ISSUE TITLE
"Sign up with Google" is not working

### ISSUE THREAD

**Issue by ucey-star** [ucey-star/ID8#41]
Description:
When a user tries to sign up using Google authentication, the application throws an error, and the Supabase URL (https://ebbjgvdnhlqubcyyikbo.supabase.com) cannot be reached. The error message displayed is:

`This site can't be reached.
Check if there is a typo in ebbjgvdnhlqubcyyikbo.supabase.com
DNS_PROBE_FINISHED_NXDOMAIN
`

**Steps to Reproduce:**
- Navigate to the application.
- Click on the "Sign up with Google" button.
- Observe the error that is displayed.

**Comment by matviikotolyk** [comment]
@ucey-star are you checking this in prod? The Google auth is working for me on the local server

**Comment by ucey-star** [comment]
Fixed
