### ISSUE TITLE
Polish the project cards

### ISSUE THREAD

**Issue by ucey-star** [ucey-star/ID8#50]
Polish the project cards
- There seem to be some redundacy in the project cards
- 
![image](https://github.com/user-attachments/assets/e1fa9012-e59a-4eff-87ce-06795223e5c8)

**Comment by matviikotolyk** [comment]
@ucey-star here's the PR for this issue: https://github.com/ucey-star/ID8/pull/59

**Comment by matviikotolyk** [comment]
PR was merged
