### ISSUE TITLE
There is no gap between the fields.

### ISSUE THREAD

**Issue by ucey-star** [ucey-star/ID8#53]
There is no gap between the fields. Thank you for implementing the comment functionality, it works fine for me, but why has the design changed (e.g., there is now a border around all the comments)? Additionally, I don’t see my name - it shows "Anonymous" instead.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e9d2c7ee-af2d-45a5-82fe-b46e50867a55">

_Originally posted by @Mykhailo-Chudyk in https://github.com/ucey-star/ID8/issues/44#issuecomment-2486744746_

**Comment by Mykhailo-Chudyk** [comment]
Already fixed
